### PR TITLE
Gmsh component

### PR DESCRIPTION
**Pull request by larsson4**
This PR adds a more complex component geometry for the linear elastic case.
Tasks:
- [x] Refactor config generation
- [x] Test if old component mesh works with new config and training
- [x] If not, define new geometry in Gmsh
- [x] Convert Gmsh geometry to MFEM
- [x]  Make component wise training work with Gmsh components

### CODE REVIEW

**Comment by larsson4** [comment]
The following code runs for me, but doesn't visualize in ParaView:
```
# Create configs for componentwise training
python3 utils/python/linelast_cwtrain.py cwtrain_optROM

# Copy to examples and build folders
rm examples/linelast/config/linelast.comp_train0.h5
cp linelast.comp_train0.h5 examples/linelast/config

rm build/examples/linelast/config/linelast.comp_train0.h5
cp linelast.comp_train0.h5 build/examples/linelast/config

rm linelast.comp_train0.h5

cd build/examples/linelast

# Debug
    ../../bin/main -i linelast.opt_comp_train.yml -f main/mode=single_run:mesh/component-wise/global_config="config/linelast.comp_train0.h5":main/use_rom=false:visualization/enabled=true:visualization/unified_paraview=false:mesh/component-wise/vertex_gap_threshold=1.0e-6:save_solution/enabled=true
    
h5dump solution.h5 > sol.txt

```

Edit: This is with the pre-Gmsh components

**Comment by larsson4** [comment]
Mesh generation with Gmsh:

```
cd ~/scaleupROM/build/utils
gmsh ~/scaleupROM/utils/gmsh/optjoint.geo -2
gmsh ~/scaleupROM/utils/gmsh/optbeam.geo -2
gmsh ~/scaleupROM/utils/gmsh/optcol.geo -2

./gmsh2mfem -m ~/scaleupROM/utils/gmsh/optjoint.msh -o 1
./gmsh2mfem -m ~/scaleupROM/utils/gmsh/optbeam.msh -o 1
./gmsh2mfem -m ~/scaleupROM/utils/gmsh/optcol.msh -o 1

mv ~/scaleupROM/utils/gmsh/optjoint.msh.mfem ~/scaleupROM/examples/linelast/meshes/optjoint.mesh
mv ~/scaleupROM/utils/gmsh/optbeam.msh.mfem ~/scaleupROM/examples/linelast/meshes/optbeam.mesh
mv ~/scaleupROM/utils/gmsh/optcol.msh.mfem ~/scaleupROM/examples/linelast/meshes/optcol.mesh

cp ~/scaleupROM/examples/linelast/meshes/optjoint.mesh ~/scaleupROM/build/examples/linelast/meshes
cp ~/scaleupROM/examples/linelast/meshes/optbeam.mesh ~/scaleupROM/build/examples/linelast/meshes
cp ~/scaleupROM/examples/linelast/meshes/optcol.mesh ~/scaleupROM/build/examples/linelast/meshes
```

**Review by dreamer2368 — CHANGES_REQUESTED** [review]
@larsson4 , would you be able to document this example in the wiki page?

**Comment by larsson4** [comment]
> @larsson4 , would you be able to document this example in the wiki page?

Yes I can. Should it replace the grid example or should we keep both?

**Review by dreamer2368 — APPROVED** [review]

**Pull request merged**
